name: Generate and Update Requirement
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt using pipreqs
        run: |
          pipreqs . --force

      - name: Commit and push requirements.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}